### Importing Libraries

In [70]:
from sqlalchemy import create_engine
import pandas as pd

### Conecting to Database

In [71]:
engine=create_engine("mysql+pymysql://root:root%40my1234352@localhost/healthcare_analysis")

### All Tables in Database

In [72]:
query="show tables;"
pd.read_sql(query,engine)

  Tables_in_healthcare_analysis
0                  appointments
1                       billing
2                       doctors
3                      patients
4                    treatments

### Importing Tables Data into Dtaframe and Basic Operations

In [73]:
query="select * from patients;"
patients_df=pd.read_sql(query,engine)
patients_df.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [74]:
patients_df.isna().sum()

patient_id            0
first_name            0
last_name             0
gender                0
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [75]:
patients_df.duplicated().sum()

np.int64(0)

In [76]:
query="select * from doctors;"
doctors_df=pd.read_sql(query,engine)
doctors_df.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com

In [77]:
doctors_df.isna().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone_number        0
years_experience    0
hospital_branch     0
email               0
dtype: int64

In [78]:
doctors_df.duplicated().sum()

np.int64(0)

In [79]:
query="select * from treatments;"
treatments_df=pd.read_sql(query,engine)
treatments_df.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [80]:
treatments_df.isna().sum()

treatment_id      0
appointment_id    0
treatment_type    0
description       0
cost              0
treatment_date    0
dtype: int64

In [81]:
treatments_df.duplicated().sum()

np.int64(0)

In [82]:
query="select * from billing;"
billing_df=pd.read_sql(query,engine)
billing_df.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [83]:
billing_df.isna().sum()

bill_id           0
patient_id        0
treatment_id      0
bill_date         0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [84]:
billing_df.duplicated().sum()

np.int64(0)

In [85]:
query="select * from appointments;"
appointments_df=pd.read_sql(query,engine)
appointments_df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,0 days 15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,0 days 14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,0 days 08:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,0 days 09:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,0 days 12:45:00,Emergency,No-show

In [86]:
appointments_df.isna().sum()

appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

In [87]:
appointments_df.duplicated().sum()

np.int64(0)

## Hospital Data Analysis

### Total Number of Patients

In [88]:
query="select count(patient_id) as Total_Patients from patients;"
pd.read_sql(query,engine)

   Total_Patients
0              50

In [89]:
query="select gender,count(*) as patients from patients group by gender;"
pd.read_sql(query,engine)

  gender  patients
0      F        19
1      M        31

### Total Number of Doctors

In [90]:
query="select count(doctor_id) as Total_Doctors from doctors;"
pd.read_sql(query,engine)

   Total_Doctors
0             10

### Total Revenue

In [91]:
query="select sum(amount) as Total_revenue from billing;"
pd.read_sql(query,engine)

   Total_revenue
0      551249.85

### Total Number of Treatments

In [92]:
query="select count(treatment_id) as Total_Treatments from treatments;"
pd.read_sql(query,engine)

   Total_Treatments
0               200

### Highest Cost Treatment

In [93]:
query="select treatment_type,cost from treatments where cost=(select max(cost) as Most_Expensive_treatments from treatments);"
pd.read_sql(query,engine)

  treatment_type     cost
0          X-Ray  4973.63

### Lowest Cost Treatment

In [94]:
query="select treatment_type,cost from treatments where cost=(select min(cost) as Most_Expensive_treatments from treatments);"
pd.read_sql(query,engine)

  treatment_type    cost
0   Chemotherapy  534.03

### Specialization Wise doctors

In [95]:
query="select specialization,count(doctor_id) as Number_of_doctors from doctors group by specialization;"
pd.read_sql(query,engine)

  specialization  Number_of_doctors
0    Dermatology                  3
1     Pediatrics                  5
2       Oncology                  2

### Branches of Hospital

In [97]:
query="select hospital_branch,count(*) as count from doctors group by hospital_branch"
pd.read_sql(query,engine)

    hospital_branch  count
0   Westside Clinic      3
1   Eastside Clinic      3
2  Central Hospital      4

### Month Wise Number of Appointments

In [98]:
query="select month(appointment_date) as month,count(*) number_of_appointments from appointments  group by month(appointment_date) order by month;"
pd.read_sql(query,engine)

    month  number_of_appointments
0       1                      20
1       2                      14
2       3                      19
3       4                      25
4       5                      19
5       6                      18
6       7                      16
7       8                      15
8       9                      11
9      10                      14
10     11                      17
11     12                      12

### Doctor with Maximum Appointments

In [99]:
query="select concat(d.first_name,' ',d.last_name) as Doctor,count(a.appointment_id) as appointments from doctors d inner join appointments a on d.doctor_id=a.doctor_id group by a.doctor_id order by appointments desc limit 1"
pd.read_sql(query,engine)

         Doctor  appointments
0  Sarah Taylor            29

### Specialization with Appointment Numbers

In [100]:
query="select d.specialization,count(a.appointment_id) as appointments from doctors d inner join appointments a on d.doctor_id=a.doctor_id group by d.specialization"
pd.read_sql(query,engine)

  specialization  appointments
0    Dermatology            70
1     Pediatrics            98
2       Oncology            32

### Appointments Status

In [101]:
query="select status,count(*) as total from appointments group by status;"
pd.read_sql(query,engine)

      status  total
0  Scheduled     51
1    No-show     52
2  Cancelled     51
3  Completed     46

### Doctor with Highest Revenue

In [102]:
query="select concat(d.first_name,' ',last_name) as Doctor,sum(t.cost) as Total_revenue from appointments a inner join doctors d on a.doctor_id=d.doctor_id inner join treatments t on a.appointment_id=t.appointment_id group by a.doctor_id order by Total_revenue desc limit 1;"
pd.read_sql(query,engine)

         Doctor  Total_revenue
0  Sarah Taylor       82696.48

### Specialization wise Revenue

In [103]:
query="select d.specialization,sum(t.cost) as Total_revenue from appointments a inner join doctors d on a.doctor_id=d.doctor_id inner join treatments t on a.appointment_id=t.appointment_id group by d.specialization;"
pd.read_sql(query,engine)

  specialization  Total_revenue
0    Dermatology      202709.29
1     Pediatrics      258937.83
2       Oncology       89602.73

### Patient with Highest Average Bill Amount

In [ ]:
query="select concat(p.first_name,' ',p.last_name) as patient,AVG(b.amount) AS avg_amount FROM patients p INNER JOIN billing b ON p.patient_id = b.patient_id group by patient ORDER BY avg_amount DESC LIMIT 1;"
pd.read_sql(query,engine)

         patient  avg_amount
0  Robert Taylor     4662.05

### Patient with Many Appoinments

In [ ]:
query="select concat(p.first_name,' ',p.last_name) as Patient,count(a.appointment_id)  as appointments from appointments a inner join patients p on a.patient_id=p.patient_id group by a.patient_id having count(a.appointment_id)= (select max(total_appointments) from (select count(appointment_id) as total_appointments from appointments group by patient_id) as appointment);"
pd.read_sql(query,engine)

       Patient  appointments
0  Laura Davis            10